<a href="https://colab.research.google.com/github/rajeshchengannur/Datascience/blob/master/session_14_numpy_advanced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy array vs Python lists

In [ ]:
# speed
# list
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []

for i in range(len(a)):
  c.a

In [ ]:
# numpy


In [ ]:
# memory

In [ ]:
# convenience

### Advanced Indexing

In [ ]:
# Normal Indexing and slicing
a=np.arange(12).reshape(4,3)
a

In [ ]:
# Fancy Indexing

In [ ]:
# Boolean Indexing
import numpy as np
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[92, 18, 22, 59],
       [21, 41, 68, 47],
       [46, 61, 71, 96],
       [95, 82, 77, 39],
       [42, 68,  6, 54],
       [25, 38, 18, 37]])

In [ ]:
# find all numbers greater than 50

In [ ]:
# find all numbers greater than 50 and are even

In [ ]:
# find all numbers not divisible by 7

### Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

The smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [ ]:
# same shape

In [ ]:
# diff shape

#### Broadcasting Rules

**1. Make the two arrays have the same number of dimensions.**<br>
- If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.<br>

**2. Make each dimension of the two arrays the same size.**<br>
- If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
- If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

<img src = "https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">

In [ ]:
# More examples

a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)

print(a)
print(b)

In [ ]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

[[0 1 2]]
[[0]
 [1]
 [2]]


In [ ]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(4,1)

print(a)
print(b)

In [ ]:
a = np.array([1])
# shape -> (1,1)
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print(b)

[1]
[[0 1]
 [2 3]]


In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)

print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


### Working with mathematical formulas

In [ ]:
# sigmoid
# mean squared error
# categorical cross entropy

### Working with missing values

In [ ]:
# Working with missing values -> np.nan

### Plotting Graphs

In [ ]:
# plotting a 2D plot
# x = y

In [ ]:
# y = x^2

In [ ]:
# y = sin(x)

In [ ]:
# y = xlog(x)

In [ ]:
# plotting a scatter plot

### Meshgrids

In [ ]:
# Meshgrids